---
# install Docker engine

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: 
      - docker
      - docker-py
    state: present
        
- name: Start docker service
  service:
    name: docker
    state: started
  register: result
  
- name: Check if Docker started
  debug:
    var: result.stdout
    
# sudo groupadd docker
#- name: Create "docker" group
#  group:
#    name: "{{ docker_group }}"
#    state: present
 
# sudo usermod -aG docker vagrant
#- name: Add remote user to docker group
#  user:
#    name: "{{ remote_user }}"
#    group: "{{ docker_group }}"
#    append: yes

# newgrp docker
#- name: reset ssh connection to login into docker group
#  ansible.builtin.meta:
#    reset_connection
  
